### PR TITLE
Update gap heat transfer syntax

### LINKED ISSUE #224: Update Bison gap heat transfer syntax
Patch deprecated syntax to prevent Bison failures when testing against VTB.

### PR DESCRIPTION
**Pull request by gambka**
Closes #224.

### CODE REVIEW

**Comment by gambka** [comment]
I don't understand. This new syntax has been in Bison for a couple months. How old is the Bison submodule in VTB?

**Comment by GiudGiud** [comment]
not that old 2023-02-13

**Comment by gambka** [comment]
We will hold off on the Bison PR until the submodule is updated here but this is ready for when that happens.

**Comment by GiudGiud** [comment]
let s see how it goes

**Comment by GiudGiud** [comment]
Fixed. Thanks for the patch!

**Pull request merged**
