### PR TITLE
Remove rz_meshgenerator parameter from ABTR workflow example

### PR DESCRIPTION
**Pull request by shikhar413**
Trying to remove rz_meshgenerator parameter from Griffin, which is used in the ABTR example but no longer needed, and is causing VTB test failures. For more info, please see https://github.inl.gov/ncrc/griffin/pull/2115 and https://civet.inl.gov/job/2464417/

### CODE REVIEW

**Comment by GiudGiud** [comment]
hi
you'll want to refer to an issue on the commit. you can use a new issue or the issue that was used for adding the model originally

**Comment by shikhar413** [comment]
Will submit an issue shortly

**Comment by shikhar413** [comment]
Refs #432

**Comment by shikhar413** [comment]
@GiudGiud PR should be good to go

**Review by GiudGiud — APPROVED** [review]
thanks for the fix

**Pull request merged**
