### PR TITLE
Remove time derivative from HPMR case. 

### LINKED ISSUE #248: Steady state HPMR model can be made less expensive
The HPMR microreactor steady state model currently includes a time derivative in the BISON heat conduction calculation. The problem, however, is steady state. This time derivative forces each BISON run to ramp up to a steady state using 50 time steps. By removing the time derivative, the overall cost of the HPMR simulation can be cut by ~50x, without affecting the results.

### PR DESCRIPTION
**Pull request by aprilnovak**
Remove unecessary time derivative from BISON solve. I also switched one of the transfers to a UserObject transfer instead of NearestNode, as it should be much faster.

Closes #248

### CODE REVIEW

**Comment by miaoyinb** [comment]
@aprilnovak My main concern is that we need to restart the steady state BISON using the checkpoint files for transient simulation. Will it work?

**Comment by aprilnovak** [comment]
I'm not sure I follow - the BISON simulation still is time-dependent, there's just not a time kernel (i.e. it still uses a transient solver). But I am also now just using one time step for BISON, a dt of 50000 (originally, it used 50 time steps, each of size 1000 seconds).

Is there a concern with that? Perhaps you can tell me which files to try running and I can test it?

**Comment by miaoyinb** [comment]
> I'm not sure I follow - the BISON simulation still is time-dependent, there's just not a time kernel (i.e. it still uses a transient solver). But I am also now just using one time step for BISON, a dt of 50000 (originally, it used 50 time steps, each of size 1000 seconds).
> 
> Is there a concern with that? Perhaps you can tell me which files to try running and I can test it?

Can you test  `microreactors/mrad/transient_null` ? 
I am worried about some time derivative variables are missing during checkpoint restoring but not sure.

**Comment by miaoyinb** [comment]
Also you may need to enable fixed point iteration between BISON and Sockeye if BISON is solved directly.

**Comment by aprilnovak** [comment]
> if BISON is solved directly.

BISON is not solved directly - it is still using a Transient executioner. You don't need time derivatives to use the transient executioner.

**Comment by GiudGiud** [comment]
The Transient executioner (and the time integrator) will take care of adding the vectors needed for time derivates to the system, even if the kernels dont use them

**Comment by miaoyinb** [comment]
> > if BISON is solved directly.
> 
> BISON is not solved directly - it is still using a Transient executioner. You don't need time derivatives to use the transient executioner. Here, the fixed point iteration is performed during the course of the Richardson iterations , right?

Sorry for the confusion. I meant, previously as we do lots of time iterations to reach "steady-state". In that case, fixed point iteration between BISON and Sockeye was found not needed as the time iterations do the job effectively. If you are solving BISON using one or only a few time steps, you may still need the fixed point interaction.

**Comment by aprilnovak** [comment]
>  If you are solving BISON using one or only a few time steps, you may still need the fixed point iteration.

In this case, I don't think you need the fixed point iteration. Griffin is already doing Richardson iterations, each of which is doing a BISON-Sockeye solve. So, if Griffin does 10 Richardson iterations, that's like doing 10 Picard iterations (evolving all the physics concurrently, rather than over-converging BISON-Sockeye when Griffin is not yet converged).

The converged solution looks identical to that on the VTB images.

**Comment by miaoyinb** [comment]
> > If you are solving BISON using one or only a few time steps, you may still need the fixed point iteration.
> 
> In this case, I don't think you need the fixed point iteration. Griffin is already doing Richardson iterations, each of which is doing a BISON-Sockeye solve. So, if Griffin does 10 Richardson iterations, that's like doing 10 Picard iterations (evolving all the physics concurrently, rather than over-converging BISON-Sockeye when Griffin is not yet converged).
> 
> The converged solution looks identical to that on the VTB images. The files I used took about 480 core-hours to complete, so I estimate that the original files take something like 24000 core-hours.

Please run a `transient_null` just to ensure the steady state is real.

It is weird that it took you 24k core-hours. I had a run that took ~4k core-hours back in Feb and I think I already used too many cores (that is before the slack discussion).

**Comment by aprilnovak** [comment]
Sure, I will try it and post an update here.

I am new to Griffin, but running with 40 ranks (which the VTB shows as the example) takes super long. I think a lot of it is due to the nearest node transfers though. Even with `fixed_meshes`, each of those transfers takes several minutes (and if BISON runs 50x per Griffin iteration, that is a lot of transfer time).

**Comment by GiudGiud** [comment]
GeneralField any better?

**Comment by aprilnovak** [comment]
Yes, so much better! It went from like 5 minute transfer to 10 seconds.

**Comment by aprilnovak** [comment]
I ran the `transient_null` case. I'm not sure it did anything. Here's what I see at the end:

```
Loading solution from the binary file ./ss/40/processor-0.bin ... done!
Start preparing element data.
Element data prepared after 78.1022 seconds.
Start assembling Elemental matrices.
Elemental matrices assembled after 78.4386 seconds.
No cyclic dependencies found in reflecting boundary conditions
```

It didn't run any time steps or create output files. What is the normal behavior?

**Comment by GiudGiud** [comment]
nice. I need to update all models to use GeneralField

**Comment by miaoyinb** [comment]
> I ran the `transient_null` case. I'm not sure it did anything. Here's what I see at the end:
> 
> ```
> Loading solution from the binary file ./ss/40/processor-0.bin ... done!
> Start preparing element data.
> Element data prepared after 78.1022 seconds.
> Start assembling Elemental matrices.
> Elemental matrices assembled after 78.4386 seconds.
> No cyclic dependencies found in reflecting boundary conditions
> ```
> 
> It didn't run any time steps or create output files. What is the normal behavior?

It's supposed to run a few time steps and you should watch the integrated power evolution. If the steady state you get is real, the power should remain constant.

I took a look at your changes. I think the end time of steady state BISON is not at zero, that might be the issue.

**Comment by GiudGiud** [comment]
@joshuahansel this trivial change which I undid in the last commit is causing a diff in Sockeye
see the diff here:
https://civet.inl.gov/job/1801563/
the commit undoing the change:
https://github.com/idaholab/virtual_test_bed/pull/249/commits/e6fe0c5766358b59000ffa16892f674c489a5600

I can merge with the change undone but this deserves attention
either that or I messed up when I deleted the column for the PP but I dont think I did?

**Review by GiudGiud — APPROVED** [review]
I verified that the change in model results is justified.

A note that what @aprilnovak achieves a better (more converged) steady state than what we had. If you look at the previous results, it was still moving though not very fast, to steady state. This trick is not always possible, but when it is it's worth it. 

Thank you again for the PR! We got busy on our own vtb deliverables, sorry for the delay. I ll get to your next PR which builds on this I think

**Pull request merged**
