### PR TITLE
Fixing SFR tests Refs #338

### PR DESCRIPTION
**Pull request by kyriv1980**
This PR resolves issue #338

### CODE REVIEW

**Comment by GiudGiud** [comment]
you need to update the pronghorn submodule too. right now with the old version, you are now failing the test:
https://civet.inl.gov/job/1975618/

**Comment by kyriv1980** [comment]
> you need to update the pronghorn submodule too. right now with the old version, you are now failing the test: https://civet.inl.gov/job/1975618/

That error was cause by a typo. We were testing for a variable (Sij) that doesn't exist.

**Comment by kyriv1980** [comment]
Tests are passing now.

**Comment by GiudGiud** [comment]
yup looks good. thanks for the patch

**Review by GiudGiud — APPROVED** [review]

**Pull request merged**
