### PR TITLE
Fix boundary with an inclusion in sfr assembly input

### PR DESCRIPTION
**Pull request by GiudGiud**
New PR in griffin catches this mesh issue (and so is MOOSE with upcoming mesh diagnostics)

### CODE REVIEW

**Comment by YaqiWang** [comment]
@GiudGiud looks like this `Mesh/remove_internal_sides/include_only_external_sides` is from your change in MOOSE?

**Comment by GiudGiud** [comment]
It s recent yes. I might have to update the griffin submodule but hopefully not

**Comment by GiudGiud** [comment]
Yeah I ll do that

**Comment by GiudGiud** [comment]
SAM timeouts unrelated

**Pull request merged**
