### PR TITLE
Regold TRISO test to accommodate UCO FGR BISON model modifications

### LINKED ISSUE #445: Regold TRISO test to accommodate UCO FGR BISON model modifications
## Reason
Modifications to the UCO FGR model in BISON require regolding a TRISO test (`triso_1d_bison`).

## Design
Regold TRISO test.

## Impact
Regold TRISO test.

### PR DESCRIPTION
**Pull request by hirsja**
Closes #445

### CODE REVIEW

**Comment by GiudGiud** [comment]
Hello

To regold you also should update the bison submodule in the VTB in apps/bison. 

Otherwise I suspect your regold will trigger a test failure

**Comment by hirsja** [comment]
Thanks @GiudGiud. I'm relatively new to VTB, so this is a bit of a learning process. I appreciate the help.

**Review by GiudGiud — APPROVED** [review]
BC failures expected, will be resolved on submodule update

**Comment by GiudGiud** [comment]
Thanks for the patch!

**Pull request merged**
