### PR TITLE
Update to MSFR 1-D system model

### PR DESCRIPTION
**Pull request by hapfang**
This PR contains the improvements to the existing documentation of MSFR 1-D system model, and includes transient modeling results induced by the primary pump head change. #172.

### CODE REVIEW

**Comment by hapfang** [comment]
Hi @GiudGiud, the documentation related to this PR has already been fully approved at ANL. Please help review and approve it at your convenience. Thanks.

**Review by GiudGiud — CHANGES_REQUESTED** [review]
new inputs will need testing

these two inputs are basically the same right? do we need to check both files?

**Comment by hapfang** [comment]
The new steady-state model (`standalone_sam_model/msfr_1d_ss.i`) is different from the previous one (` msfr_system_1d.i`). The new one uses SAM PKE model, and have the improved EOS specifications. For the CI test, I would recommend to do it for the new input model. There are also input files for the 2 transient cases: (a) 50% head loss and (b) pump trip. I think it should be fine to only include 'msfr_1d_ss.i` in the test. How do you usually generate gold reference? Feel free to let me know if you prefer me to do it.

**Review by hapfang — COMMENTED** [review]
Don't see any major changes.

**Comment by eshemon** [comment]
Any update on merging this?

**Comment by GiudGiud** [comment]
This is still red with SAM.

I ll clean up the unrelated failures in a separate PR, then clean up the commit history here. 

We are in LDRD proposal season here at INL so it might take me a few weeks

**Comment by eshemon** [comment]
OK thanks Guillaume! @hapfang  - do you need to check on the SAM failure?

**Comment by hapfang** [comment]
Hi @eshemon, yes, I have reported the test failures to the SAM developer team. The same issue also affects several other SAM models previously uploaded. I will coordinate the debugging efforts to get them all fixed. For future reference, the SAM team has agreed to include all VTB SAM models into the regular SAM test suite too. Will keep you updated.

**Comment by GiudGiud** [comment]
Removed the merge commits and rebased off of devel. I m hoping we cant get this in without any additional work.

**Comment by hapfang** [comment]
Thanks @GiudGiud.

**Comment by GiudGiud** [comment]
updated input is failing. I think we ll have to look at the fix in the SAM submodule update PR

**Comment by travismui** [comment]
> updated input is failing. I think we ll have to look at the fix in the SAM submodule update PR

@GiudGiud I took a look at this failure and made some fixes, see if you can pull [this commit](https://github.com/travismui/virtual_test_bed/commit/4fabace032911d73d00e51d3534afbe91d28dec0#diff-3f753e641b26a009dfa4597ce02cbf5895ed415cd9d2737c1244c15d53c3b2ba) onto this PR.

Fix for the convergence breakdown was to allow more nonlinear iterations, but had to make a few other updates too.

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
Looks good. Thanks for the update @hapfang and for all the patches @dogrady2 !

**Pull request merged**
