### PR TITLE
Changing figures styling of the GCMR core neutronic model

### LINKED ISSUE #392: Improving the styling of GCMR figures
## Bug Description
The figures of the GCMR microreactor core are not displaying correctly.

## Steps to Reproduce
Fixing the styling of GCMR figures.

## Impact
Present the models more effectively and improve the documentation.

### PR DESCRIPTION
**Pull request by aabdelhameedd**
closes #392

### CODE REVIEW

**Comment by GiudGiud** [comment]
Is it showing for you here?

https://mooseframework.inl.gov/virtualtestbed/docs/PRs/393/site/microreactors/gcmr/GCMR_Core_Neutronics.html

**Comment by aabdelhameedd** [comment]
> Is it showing for you here?
> 
> https://mooseframework.inl.gov/virtualtestbed/docs/PRs/393/site/microreactors/gcmr/GCMR_Core_Neutronics.html

Nope. I'm not sure of the reason. Should we remove all the styling?

**Comment by GiudGiud** [comment]
Let's try that

**Comment by aabdelhameedd** [comment]
> Let's try that

It hasn't resolved the problem. I'll attempt using an alternative photo file format.

**Comment by aabdelhameedd** [comment]
> > Let's try that
> 
> It hasn't resolved the problem. I'll attempt using an alternative photo file format.

Now worked! after changing the photo file format.  Looks good to me now!

**Comment by GiudGiud** [comment]
Perfect

What was the format that did not work? We can add an error in moose for those

**Review by GiudGiud — APPROVED** [review]
Looks like png. Must be a version of png or something

**Comment by aabdelhameedd** [comment]
> Perfect
> 
> What was the format that did not work? We can add an error in moose for those

It's quite puzzling since I only switched from the PNG to the JPG format. I'm certain that PNG files have worked fine for me with other models in the past.

**Pull request merged**
