### PR TITLE
Submodule update, refs #0

### PR DESCRIPTION
**Pull request by GiudGiud**

### CODE REVIEW

**Comment by GiudGiud** [comment]
@dogrady2 @travismui I m getting some diffs when updating the SAM submodule. I think some of these inputs you have checked in SAM too so maybe you already have the fix?
https://civet.inl.gov/job/2199345/

**Comment by travismui** [comment]
> @dogrady2 @travismui I m getting some diffs when updating the SAM submodule. I think some of these inputs you have checked in SAM too so maybe you already have the fix? https://civet.inl.gov/job/2199345/

@GiudGiud We caught this in our weekly pipeline, but no fix yet for the generic PBR or MSFR test. I'll take a look at this tomorrow or early next week.

**Comment by GiudGiud** [comment]
sounds good, thanks!

**Comment by GiudGiud** [comment]
Any luck @travismui ?

**Comment by travismui** [comment]
> Any luck @travismui ?

Still a WIP, there was some overhaul of the PKE model in SAM resulting in some of these diffs so we're sorting through a handful of models to make sure it's still consistent. I'll have a separate branch and/or PR to address the fixes.

**Comment by GiudGiud** [comment]
Sounds good thanks for the updated

**Comment by GiudGiud** [comment]
The MCRE neutronics input runs with a newer Griffin so the old version of BC is the problem for that coupled multiphysics calculation reporting an error on the neutronics mesh.

This will be settled once SAM submodule can be updated
Other failures are timeouts

**Pull request merged**
