### PR TITLE
fix subchannel testing Refs #257

### PR DESCRIPTION
**Pull request by kyriv1980**
This PR resolves issue Refs #257

### CODE REVIEW

**Comment by kyriv1980** [comment]
Pronghorn test should pass once my latest subchannel PR gets merged.

**Comment by GiudGiud** [comment]
ok once this in Pronghorn devel, we ll want to change the apps/pronghorn in the VTB to that version

**Comment by kyriv1980** [comment]
@GiudGiud , the new version of subchannel has been merged to the level branch. Do we need to manually update pronghorn/the pronghorn version used in VTB? Or it will propagate automatically?

**Comment by GiudGiud** [comment]
need to update the submodule in this PR

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
Test failures are unrelated.

Thank you for the patch!

**Pull request merged**
