### PR TITLE
SAM submodule update

### PR DESCRIPTION
**Pull request by GiudGiud**
Getting some failures (like 9) on this submodule update
This is preventing us from updating the MSFR 1D module

I got a few of them, but could I please get help for the others? @dogrady2 
There's some larger diffs on the VTR and I m not sure why I lost good convergence on the FHR primary ?

@rui-hu we should start testing VTB on SAM PRs. 
This is done for every other NEAMS app (well except SAM& Cardinal at this point) btw, we could share the civet recipe if you dont have it.

### CODE REVIEW

**Comment by GiudGiud** [comment]
The pbr test is actually a diff too at this point.
This input used to pass 6 steps and now it crashes on step 2, 3 & 4

**Comment by rui-hu** [comment]
@GiudGiud it seems that I cannot see the civet test results. Could someone help resolve the issue for us?

**Comment by GiudGiud** [comment]
Which login are you using? github/ ANL CELS / ANL EGS or INL ?

**Comment by rui-hu** [comment]
@dogrady2 , please take a look at the failed test cases. 
@GiudGiud , I believe we are already in discussion of including VTB test cases in our regression test. @dogrady2 , if you need any helps, please ask @GiudGiud .

**Comment by rui-hu** [comment]
by default, it used my ANL(ANL EGS) account.

**Comment by GiudGiud** [comment]
@milljm what login should we use to view SAM results here?

**Comment by milljm** [comment]
Copy/Paste from an email that went out to all NCRC individuals:

At your earliest convenience, please navigate and login to [github.inl.gov](https://github.inl.gov). To login, follow the instructions depending on your status:

- INL Employee: If in the office or on VPN: Enter your INL e-mail address at the login screen. If not on VPN (home network, etc.): Sign in with your badge (Click 'Sign in with PIV / CAC card')

- External (non-INL) user): Enter your HPC e-mail address, your HPC password, and then your HPC RSA PIN + token. You must have an RSA token issued by HPC to use this service. If you do not have a token, contact [hpcsupport@inl.gov](mailto:hpcsupport@inl.gov)  to obtain one.

**Comment by GiudGiud** [comment]
@rui-hu could you try the github.inl.gov login?

**Comment by GiudGiud** [comment]
Actually I think the canon way to get access to test results was for me to add you to the repo team. You should have an invitation in your inbox @rui-hu

**Comment by rui-hu** [comment]
Thanks @GiudGiud. I can see the test results with my github account now. could you add @dogrady2 to the repo as well?

**Comment by GiudGiud** [comment]
Should already be in

**Pull request closed without merging**
