### PR TITLE
Used MSRNeutronicsFluidCoupling syntax

### LINKED ISSUE #410: Utilize MSRNeutronicsFluidCoupling
## Reason
The `MSRNeutronicsFluidCoupling` was created to simplify the coupling of neutronics and fluids for MSRs, and this should be demonstrated.

## Design
This would modify some inputs to the MSFR example to use the `MSRNeutronicsFluidCoupling` syntax.

## Impact
Input file changes.

### PR DESCRIPTION
**Pull request by joshuahansel**
Closes #410

### CODE REVIEW

**Comment by GiudGiud** [comment]
Fails tests due to a different time step history. See https://github.com/idaholab/moose/pull/27257 for when the time step history started to be tougher to keep being the same

**Comment by GiudGiud** [comment]
Doco failure is due to the use of !include in the input file.
we already merged a fix in moose, but something doco-related is actually split-off from moose now (moose-pyhit? @milljm knows) so it's not updated

**Comment by joshuahansel** [comment]
Thanks, the documentation failures make sense and I think I've fixed them now. I didn't see anything about `!include` but I could be blind. The failures were because documentation was trying to list now-nonexistent blocks in the input file. I'll look into the diff.

**Comment by GiudGiud** [comment]
oh ok maybe i misdiagnosed the doco failure

**Comment by joshuahansel** [comment]
I'm running the tests locally with VTB's current BC (9674843ae7bc24d3ea9ae86bcb09fb526c0fad9b), and I'm getting segmentation faults. No stop triggered in LLDB with dbg, so I'm unsure what to do next. It seems to occur only for MSFR inputs with fluids, after the initial fluids residual evaluation. I see it even on tests where I did not use my new syntax, like `msr/msfr/plant/steady.core_fluids_only`. I'm looking into it.

**Comment by joshuahansel** [comment]
Tried it on my laptop too. Same result.

**Comment by joshuahansel** [comment]
@GiudGiud Do you mind trying testing it on your machine when you get a chance?

**Comment by GiudGiud** [comment]
will take a me a bit.
one machine is locked out, the other one is hosed, and the last is a personal one and I dont install BC on it. I ll HPC this

**Comment by joshuahansel** [comment]
What I've tried:

- Mac Pro, VTB BC version : segfault
- MacBook Pro, VTB BC version : segfault
- MacBook Pro, devel BC version: segfault
- current HPC binary: no segfault (fail due to other reasons)

Versions:

- VTB BC version is 9674843ae7bc24d3ea9ae86bcb09fb526c0fad9b (July 17)
- current HPC BC version is 5bf7cd8 (June 28)
- devel BC version is d938bde4a40e46d6bd678c5f07c6b1139181f968 (Aug 8)

I'll try building VTB BC version on HPC.

**Comment by joshuahansel** [comment]
Updated list in previous comment: no failure with BC I compiled on HPC, just on Macs.

**Comment by GiudGiud** [comment]
BC is running fine for me on my mac too. I think this might be tied to my post in dev-ops in #moose. 

anyway, I m updating the submodules and the MSFR failures. This should be good to go after

**Comment by joshuahansel** [comment]
> BC is running fine for me on my mac too

Thanks for checking. Tried again with newest BC and still segfaults 😢

**Comment by GiudGiud** [comment]
your mac is cursed

**Comment by GiudGiud** [comment]
do you mind addressing the doco failure? The rest of the stack will be ready.

imo the failure is the thing I mentioned early still but happy to be proven wrong

**Comment by joshuahansel** [comment]
Yeah I'll push up the doc fix now.

> imo the failure is the thing I mentioned early

Which failure are you talking about? doc? Or diffs? Or segfault?

If diffs, I guess you mean

> Fails tests due to a different time step history. See https://github.com/idaholab/moose/pull/27257 for when the time step history started to be tougher to keep being the same

**Comment by GiudGiud** [comment]
> Which failure are you talking about? doc? Or diffs? Or segfault?


I mean the doco failure

**Comment by joshuahansel** [comment]
Ah ok, yep, I believe you are right about the doc. I had tested locally and after fixing the doc errors I mentioned, it built fine, but I guess a more recent MOOSE (environment? since there's no executable in VTB?) was used locally or something.

**Review by GiudGiud — APPROVED** [review]
thanks for the contribution!

**Comment by joshuahansel** [comment]
Thanks for doing all of the support work!

**Pull request merged**
