### PR TITLE
Remove exceptions and use correct app. 

### LINKED ISSUE #15: Remove exceptions from OCCA kernels
Exceptions actually aren't available on GPUs, so these additional error checks need to be removed from the OCCA kernels for the NekRS inputs so that someone could run them on GPUs if desired.

### PR DESCRIPTION
**Pull request by aprilnovak**
This PR removes exceptions from the Cardinal examples (which will not work on GPUs). Also updates to the latest Cardinal syntax.

Closes #15

### CODE REVIEW

**Comment by aprilnovak** [comment]
Do I need to do something special to get access to see the test results? Clicking on the link sends me to a page that says I don't have permissions, but I am already logged in via github.

**Comment by GiudGiud** [comment]
@permcody

**Comment by GiudGiud** [comment]
There's an ANL CELS and EGS login, can you log in with that?
We dont have cardinal in the test suite yet anyway

**Comment by GiudGiud** [comment]
@aprilnovak you needed to be added to a group with read access to the repo to have the test suite be ran automatically. 
Can you access test results now?

**Comment by aprilnovak** [comment]
Yes, I can access the test results now - thank you! Apologies for not responding right away

**Pull request merged**
