### PR TITLE
Re-gold mesh only tests to account for bug fixes pushed to MOOSE framework

### PR DESCRIPTION
**Pull request by shikhar413**
Addresses #243

### CODE REVIEW

**Comment by shikhar413** [comment]
@GiudGiud I just consulted with @miaoyinb who thinks the bison test failures are related to precision errors that are minor and can be re-golded, since the actual values are supposed to be 0 at the first time step. I've gone ahead and re-golded and tests pass.

However, it looks like the mesh only Griffin tests are still not seeing the latest exodus files that were uploaded as part of the commit and exodiff errors are still happening. Is this expected?

**Comment by GiudGiud** [comment]
Griffin is probably an older submodule which uses an older version of MOOSE

**Comment by shikhar413** [comment]
Ok, let me know if this is ready to merge. Some existing PR’s in Griffin can’t be merged until this PR is merged so that the Griffin VTB tests pass

**Comment by GiudGiud** [comment]
TImeouts are unrelated. 
dire_wolf and BC failures will be caught by a submodule update

**Comment by GiudGiud** [comment]
Thanks for the patch!

**Pull request merged**
