### PR TITLE
Update Griffin to the current devel and fix an input accordingly

### PR DESCRIPTION
**Pull request by YaqiWang**
As title.

### CODE REVIEW

**Comment by loganharbour** [comment]
@YaqiWang you can do refs #000 for a submodule update

**Comment by YaqiWang** [comment]
oh

**Comment by GiudGiud** [comment]
I m ok with merging this but we can expect failures in direwolf and bluecrab on something like this btw

**Comment by YaqiWang** [comment]
Looks like CIVET will push Griffin master into bluecrab automatically but not direwolf. Or maybe we treat direwolf same as failed but allowed for now?

**Comment by GiudGiud** [comment]
well except here we d need Griffin devel to be used in direwolf as well, then this test can pass.

**Comment by YaqiWang** [comment]
Yes. If we do auto update in direwolf, it will be good. I actually thought we possibly had it before.

**Comment by GiudGiud** [comment]
It wont, it needs to be a devel version of Griffin that gets pulled, not the master.
This is why the blue crab recipe is failing.

I think the current process would be to update the submodules in blue crab and dire wolf to Griffin devel, then they can pass here.

**Comment by YaqiWang** [comment]
If both are failed and allowed, then Griffin can move things from devel to master and be able to update bluecrab. If we do that for direwolf, it can update direwolf as well. This is one of the example I was talking: https://moosebuild.hpc.inl.gov/job/393031/.

**Comment by loganharbour** [comment]
> Or we make VTB as failed but allowed, then once things reach Griffin master and all depending apps master, we can just update submodules for VTB. What do you think?

The problem with that is that we can't trust most people to not merge things that break VTB :-)

**Comment by YaqiWang** [comment]
I am having headache again on this... I do not have access to direwolf anyway. We do not have auto submodule update for VTB, right?

**Comment by GiudGiud** [comment]
Yeah it really depends on who we want to give the job of updating those two. I'm fine with allowed to fail in VTB for these two, then automatic submodule updates take care of making it pass between VTB devel and VTB main

**Comment by GiudGiud** [comment]
no automatic submodule update in VTB yet yes, but it is coming

**Comment by YaqiWang** [comment]
Can we let VTB direwolf use VTB griffin? In this way, the test will pass.

**Comment by GiudGiud** [comment]
I dont know how to do that apart from making a PR to direwolf.

I m merging on failing as this will self-resolve for blue crab, and resolve when I make a PR for direwolf

**Comment by YaqiWang** [comment]
@GiudGiud or @loganharbour Why we are still seeing this https://moosebuild.hpc.inl.gov/job/393516/? Maybe this MR has not made its way into the master branch?

**Comment by loganharbour** [comment]
> @GiudGiud or @loganharbour Why we are still seeing this https://moosebuild.hpc.inl.gov/job/393516/? Maybe this MR has not made its way into the master branch?

Guillaume explained this above:

> It wont, it needs to be a devel version of Griffin that gets pulled, not the master.
This is why the blue crab recipe is failing.
> 
> I think the current process would be to update the submodules in blue crab and dire wolf to Griffin devel, then they can pass here.

you can see on civet.inl.gov that devel is failing.

**Comment by YaqiWang** [comment]
That test (I invalidated half hour ago) is still testing against old VTB. With this change, I've updated the failing input and we should not see the error.

**Comment by GiudGiud** [comment]
this MR is not making it into master because direwolf is failing. We need to update the recipe to allow to fail on dire wolf
OR update griffin submodule in dire wolf

**Comment by loganharbour** [comment]
> That test (I invalidated half hour ago) is still testing against old VTB.

https://civet.inl.gov/branch/13349/ you can see devel here..

**Pull request merged**
