### PR TITLE
Add first bison triso input

### PR DESCRIPTION
**Pull request by jiangwen84**
ref #100

### CODE REVIEW

**Comment by jiangwen84** [comment]
@GiudGiud  Could you enable my account for testing?

**Comment by jiangwen84** [comment]
@GiudGiud  Could you help with fixing this error `Did not create BISON` ?   I guess I do not understand how different app is set up in this repo. Thanks.

**Comment by GiudGiud** [comment]
my guess is that --app BisonApp doesnt work for Bison
let me try something

**Comment by GiudGiud** [comment]
ok looks like not. I ll have a look

**Comment by jiangwen84** [comment]
@GiudGiud  did you get a chance to look at that issue? thanks.

**Comment by GiudGiud** [comment]
not yet. I will as soon as I can

**Comment by jiangwen84** [comment]
@GiudGiud I was in the Bison training in the last two days. I will try to tight the tolerance tomorrow and we will see if blue crab could pass.

**Comment by GiudGiud** [comment]
BlueCrab should follow the same execution path though. We need to understand what action is ran by Bison and not by BlueCrab or vice versa. 

My experience is that if we don’t find out now, someone else will run into this and it ll come up again. Do you have BlueCrab?

**Comment by GiudGiud** [comment]
Also to pass the test we can just run with —app in BlueCrab. But this won’t uncover the reason for the diff

**Comment by GiudGiud** [comment]
seems not. Ok that diff seems legitimate

**Comment by GiudGiud** [comment]
I've tried for a bit to work with the convergence criteria. To no avail.

**Comment by jiangwen84** [comment]
@GiudGiud Could you merge this PR if you do not have any other comments?

**Review by GiudGiud — APPROVED** [review]

**Pull request merged**
