### PR TITLE
Added cardinal as executable pattern to test.

### PR DESCRIPTION
**Pull request by pbehne**
Added cardinal to executable pattern for test. Related to #399.

### CODE REVIEW

**Comment by GiudGiud** [comment]
need a reference to an issue

**Review by GiudGiud — APPROVED** [review]

**Comment by gambka** [comment]
I guess `RunCommand` test types do not have the `executable_pattern` option.

**Comment by GiudGiud** [comment]
looks like it. Let s use the required python package then

**Comment by GiudGiud** [comment]
this explains why it was not there

**Review by GiudGiud — APPROVED** [review]

**Pull request merged**
