### PR TITLE
Signal checkpoint patch

### PR DESCRIPTION
**Pull request by pbehne**
Fixing checkpoint execute_on. Ref #1234.

### CODE REVIEW

**Review by GiudGiud — CHANGES_REQUESTED** [review]
save the files without formatting (ctrl P to get the option in VSCode)

**Comment by pbehne** [comment]
> save the files without formatting (ctrl P to get the option in VSCode)

Done.

**Comment by GiudGiud** [comment]
This should not be necessary

**Comment by pbehne** [comment]
Closing, as execute_on FINAL is still allowed.

**Pull request closed without merging**
