### PR TITLE
Necessary change due to the addition of neon.

### PR DESCRIPTION
**Pull request by atoptann**
Necessary change due to the addition of neon as the inert gas option in GapConductanceLWR, Bison. See Bison MR !3390

### CODE REVIEW

**Comment by recuero** [comment]
I cannot see these tests on CIVET but it looks as if there is something failing on precheck.

**Comment by atoptann** [comment]
> I cannot see these tests on CIVET but it looks as if there is something failing on precheck.

Missing a valid ticket reference!

**Comment by GiudGiud** [comment]
I ll update that in a minute

**Comment by atoptann** [comment]
> I ll update that in a minute

thanks!

**Comment by GiudGiud** [comment]
Needs a bison submodule update too. 
I ll add that

**Comment by GiudGiud** [comment]
next step is to merge the bison MR, then update the bison submodule to bison/devel in this PR, which will then pass, be merged, then bison/devel will be green on the VTB
@atoptann please let me know if there's any issues

**Comment by recuero** [comment]
It turns out I cannot merge with a broken pipeline. Can we do it the other way, i.e. break VTB with this PR and then pull new VTB repo for Bison testing?

**Comment by atoptann** [comment]
> It turns out I cannot merge with a broken pipeline. Can we do it the other way, i.e. break VTB with this PR and then pull new VTB repo for Bison testing?

I think that would be easier and faster.

**Comment by GiudGiud** [comment]
VTB will not merge to main while broken either.
You should be able to merge with a failing test. @gambka can you have a look

**Comment by gambka** [comment]
> VTB will not merge to main while broken either. And Bison testing tests vtb/main not vtb/devel You should be able to merge with a failing test. @gambka can you please have a look to trigger the merge on the bison side

I have the same merging privileges as @recuero on BISON. We may have to temporarily modify the CIVET script on BISON to be allowed to fail.

**Comment by recuero** [comment]
It may make sense to bump up some of our privileges to handle these cases. No one that works with Bison seems to have the required privileges to do this type of merges.

**Comment by atoptann** [comment]
All the problems are solved now. Thanks for the help!

**Comment by GiudGiud** [comment]
BlueCrab will keep failing until BISON submodule updates there

**Pull request merged**
