### PR TITLE
Update blue crab submodule

### PR DESCRIPTION
**Pull request by GiudGiud**
refs #0

### CODE REVIEW

**Comment by GiudGiud** [comment]
The level of output of some generators here are ludicrous. I m going to fix that upsteam in MOOSE then come back here to fix the inputs. 

This will delay the VTB fixing

**Comment by loganharbour** [comment]
please make sure when you actually merge it that you use a master hash

**Comment by loganharbour** [comment]
please make sure to use a master commit

**Comment by GiudGiud** [comment]
we don't need to do this right now, this is to trigger the test suite. And as you know the current commit or the current master are not workable right now.

**Comment by loganharbour** [comment]
> we don't need to do this right now, this is to trigger the test suite. And as you know the current commit or the current master are not workable right now.

that's fine - say that instead of deleting a comment

**Comment by GiudGiud** [comment]
A few updates on this:
- verbosity in MOOSE has been fixed for stitiching meshes
- verbosity in Griffin is being fixed by @YaqiWang 
- action ordering issue between SAM and bison should be fixed once this goes in
https://git-nse.egs.anl.gov/SAM/SAM/-/merge_requests/713

**Comment by GiudGiud** [comment]
We're down to 5 errors
3 are SAM-BC interaction related and will have to be addressed separately
One is a crash with the checkpoint system which we'll address when we fix this #18957
The last one is an unexplained diff. 

For the safe of integrating other models, I ll move forward in this state

**Comment by GiudGiud** [comment]
and now that I've merged I think I know what the crash was..

**Pull request merged**
