### PR TITLE
New convention to declare gap gas fractions

### PR DESCRIPTION
**Pull request by atoptann**
New convention to declare gap gas fractions in Bison.  refs idaholab#6

### CODE REVIEW

**Comment by atoptann** [comment]
@GiudGiud

**Comment by GiudGiud** [comment]
For this PR to pass we need to update the BISON submodule in the apps/bison directory. 

Did the relevant PR in Bison get merged ?

**Comment by GiudGiud** [comment]
Actually this is a diff on the test result. Did something else than the syntax change in bison?

**Comment by GiudGiud** [comment]
A submodule update fixed the problem. However, the deprecation was not done properly on the BISON side because a diff happened with no complaining between the new and old syntax.

**Comment by GiudGiud** [comment]
It should have errored before on unused parameters actually?

**Pull request merged**
