### PR TITLE
Loose tolerance of bison triso test

### LINKED ISSUE #114: Loose tolerance of Bison TRISO test
Bison MRs failed because of CSV diff of VTB's TRISO input file. We need to loose the tolerance a bit.

### PR DESCRIPTION
**Pull request by jiangwen84**
closes #114

### CODE REVIEW

**Comment by jiangwen84** [comment]
@gambka reported that VTB TRISO test caused csvdiff on Bison MRs. 

@GiudGiud could you merge this to let Bison MRs to pass? I believe the tolerance is now loose enough to pass all MRs.

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
The VTB has merged to main so you should be pulling the right one
https://civet.inl.gov/branch/13349/

I think the test is breaking the other criterion, the rel_diff not the abs_diff

**Comment by jiangwen84** [comment]
The Bison MRs failed due to rel_tol. I can loose it further, but just curious why it will pass here but not Bison MRs. Any thoughts?

**Comment by GiudGiud** [comment]
It s not surprising since it diffs between my Mac and civet, it can diff between diffeeent machines on civet

I doubt there are any differences between the two testing recipes ran

**Comment by GiudGiud** [comment]
I ll put a PR right now, have to look at BC tests anyway.

**Comment by jiangwen84** [comment]
Sounds good. You can set the rel_tol = 1e-3. That should be sufficient.

**Comment by GiudGiud** [comment]
ok I merged the looser tolerance. Still passes on VTB PRs, hope bison PRs are good too

**Pull request merged**
