### PR TITLE
Regold due to minor changes in GraphiteMatrixThermal

### LINKED ISSUE #228: Regold Bison tests containing GraphiteMatrixThermal
A change in the density warning in Bison in the `GraphiteMatrixThermal` class has resulted in minor csvdiffs to a few simulations that use it in the VTB. Regold the inputs as the changes are expected.

### PR DESCRIPTION
**Pull request by gambka**
Closes #228

### CODE REVIEW

**Comment by GiudGiud** [comment]
Thanks for the patch.
Just a note, this wont pass bluecrab for a bit, until BC has the right bison submodule.

**Comment by gambka** [comment]
> Thanks for the patch. Just a note, this wont pass bluecrab for a bit, until BC has the right bison submodule.

Our blue crab testing on Bison devel shows that it is passing just fine.

**Comment by GiudGiud** [comment]
BC hasnt been updated on vtb yet, so it still has an older bison

**Comment by gambka** [comment]
> BC hasnt been updated on vtb yet, so it still has an older bison

Do you want me to submit a separate PR for a BC submodule update?

**Comment by GiudGiud** [comment]
nope no need. Just logging what we're doing

**Pull request merged**
