### PR TITLE
Add cardinal submodule

### PR DESCRIPTION
**Pull request by loganharbour**

### CODE REVIEW

**Review by GiudGiud — APPROVED** [review]

**Comment by GiudGiud** [comment]
@aprilnovak 
anything we could do better to get all green on cardinal? What are your thoughts on these two nek inputs from the pbfhr reflector? 
What are the current failures from? Logan mentioned some jit issue?
Do you thing we ll be able to get a few time steps in 300s on 16 cores?

**Comment by aprilnovak** [comment]
Errors like this means that Nek has run out of memory:

```
relocation truncated to fit: R_X86_64_PC32 against `.bss'
```

Unfortunately the Nek simulations are pretty big. What approach is VTB taking for the other non-Cardinal Nek models (like the MSR)?

**Comment by aprilnovak** [comment]
And I can fix the `run_openmc` test - that input file as-is can't be run outside of the multi-app coupling (its initial temperatures are set by MOOSE, but running just the standalone input file causes those initial temperatures to be set to zero, hence the error). It just needs a minor change.

**Comment by GiudGiud** [comment]
ok let me try this initialization and giving the other one more cores (so more memory probably? @loganharbour )

then I ll think it ll be enough for this one and we can pursue this in another PR

**Comment by GiudGiud** [comment]
Well I tried. 
Those 3 tests will be fixed in a later PR if possible. 2 of them are stretching our testing infrastructure, one may require more analysis

**Comment by loganharbour** [comment]
We could start transitioning some testing to HPC machines if needed

**Comment by GiudGiud** [comment]
From the docs it seems we only need 48 cores to run them.
Build farm has this, but should VTB get a pass on using that much computing?

**Comment by loganharbour** [comment]
Each EPYC machine is 64 procs per machine, split up into 3 clients

**Comment by GiudGiud** [comment]
any way to book the full machine for VTB tests?

**Comment by loganharbour** [comment]
Nope

**Pull request merged**
