### PR TITLE
Modify CSS to meet issue request

### LINKED ISSUE #305: Improve CSS for resources/filter page
## Feature Description
I was asked to make this page more 'mooseframework-like'.

## Design
Modify the CSS to match those of moose.css.

## Impact
Similar appearances between VTB and mooseframework.org web packages

### PR DESCRIPTION
**Pull request by milljm**
Added official INL color attributes.

Added @media extensions (dark-mode).

Adjusted several other rules to allow more information on smaller screens.

Closes #305

### CODE REVIEW

**Comment by milljm** [comment]
Let me know if you need the CSS minified...

**Comment by milljm** [comment]
To be compared against: https://mooseframework.inl.gov/virtual_test_bed/resources/filter/

**Comment by milljm** [comment]
Hmmm Civet is sending the wrong "View the site here link". I'll look into this tomorrow. In the meantime, we _are_ properly serving PR sites for VTB.

https://mooseframework.inl.gov/virtual_test_bed/docs/PRs/306/site/

**Comment by permcody** [comment]
This looks good - More to do, but we'll start with this!

**Comment by milljm** [comment]
Fixed the URL links. The following should now work.

> Job [VTB Documentation](https://civet.inl.gov/job/1843727/) on [1a26ac0](https://github.com/idaholab/virtual_test_bed/commit/1a26ac00e1bba7a895311dd3c18bccd6b27a8e0a) wanted to post the following:
> 
> View the site [here](https://mooseframework.inl.gov/virtualtestbed/docs/PRs/306/site)
> 
> This comment will be updated on new commits.

**Pull request merged**
