### PR TITLE
Trivial regolding for two tests due to the change on outputting extra element integers

### LINKED ISSUE #365: Patch is required for MOOSE PR 27026
## Feature Description
MOOSE PR 27026 (https://github.com/idaholab/moose/pull/27026) changes how extra element integers are outputted. Basically, all extra element integers added after mesh setup will not be outputted. This requires two trivial regoldings of HTR10 tests using Griffin.

## Design
Regolding is trivial because the gold files do not contain those extra element integers, which are not outputted properly.

## Impact
No capability impact.

### PR DESCRIPTION
**Pull request by YaqiWang**
https://github.com/idaholab/moose/pull/27026

Tag @lindsayad and @GiudGiud 

Closes #365.

### CODE REVIEW

**Comment by YaqiWang** [comment]
The change in XML file is to remove a warning caused by an outdated attribute `InMeter` in the file.

**Comment by GiudGiud** [comment]
Regolding is fine but could we get away with ignoring the field instead? In the tests specs. There should be a shorthand for ignoring fields

**Comment by YaqiWang** [comment]
There is. But I think regolding is possibly preferred.

**Comment by GiudGiud** [comment]
Regold s not generally preferred. Especially with large LFS files

The PR will need a submodule update to pass
Also the cross sections file should not have changed?

**Comment by YaqiWang** [comment]
Forgot commenting the xs file. No, I do not have to change it. Just when running the model, I noticed some warnings when loading the file, so I removed the warning by remove the outdated attribute `InMeter` in the file. The two exodus files are LFS files?

**Comment by GiudGiud** [comment]
All 3 files are LFS files

**Review by GiudGiud — CHANGES_REQUESTED** [review]
avoid unnecessary regolds

**Review by GiudGiud — APPROVED** [review]

**Comment by YaqiWang** [comment]
Do I need to manually update MOOSE as well?

**Comment by YaqiWang** [comment]
@GiudGiud let me know if I need to do more on this pr. Maybe this is ready to merge.

**Comment by GiudGiud** [comment]
no but the two diffs in Griffin still needs to be fixed

**Comment by YaqiWang** [comment]
>but the two diffs in Griffin still needs to be fixed

What are those?

**Review by lindsayad — APPROVED** [review]

**Comment by lindsayad** [comment]
failures are unrelated

**Comment by GiudGiud** [comment]
Not completely unrelated but we ll resolve them with a blue crab & direwolf submodule update later on so all good

**Pull request merged**
